name: Build Windows X64 Wheels

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
    tags:
        # NOTE: Binary build pipelines should only get triggered on release candidate builds
        # Release candidate tags look like: v1.11.0-rc1
        - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version"
        required: true
        type: choice
        options:
          - Python312
          - Python311
        default: Python312
      msvc_version:
        description: "MSVC Version"
        required: true
        type: choice
        options:
          - 'latest'
          - '14.40'
          - '14.36'
        default: 'latest'
      pytorch_build_artifact_name:
        description: "Artifact name of PyTorch build run"
        required: true
        default: "pytorch-wheel"
        type: string
      build_type:
        description: "Build type"
        required: false
        type: choice
        options:
          - Release
          # - Debug not available for the wheel
        default: Release
      repository_name:
        description: "torchvision repository (username/repo)"
        required: false
        default: "pytorch/vision"
        type: string
      repository_branch:
        description: "repository branch"
        required: false
        default: "main"
        type: string
      build_version:
        description: "Optional: build version for wheel file name (e.g. 2.6.0)"
        required: false
        default: "2.6.0"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  trigger-test-infra:
    uses: alinpahontu2912/test-infra/.github/workflows/build_wheels_windows_x64_test.yml@x64windows_test
    with:
      repository_name: ${{ inputs.repository_name }}
      repository_branch: ${{ inputs.repository_branch }}
      python_version: ${{ inputs.python_version }}
      msvc_version: ${{ inputs.msvc_version }}
      build_type: ${{ inputs.build_type }}
      build_version: ${{ inputs.build_version }}
