name: Build Windows Arm64 Torchvision Wheel

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
    tags:
        # NOTE: Binary build pipelines should only get triggered on release candidate builds
        # Release candidate tags look like: v1.11.0-rc1
        - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version"
        required: true
        type: choice
        options:
          - "3.12"
          - "3.11"
        default: "3.12"
      build_type:
        description: "Build type"
        required: true
        type: choice
        options:
          - Release
          # - Debug (not supported for wheel)
        default: Release
      repository_name:
        description: "torchvision repository (username/repo)"
        required: false
        type: string
        default: "pytorch/vision"
      repository_branch:
        description: "repository branch"
        required: false
        type: string
        default: "main"

permissions:
  id-token: write
  contents: read

jobs:
  trigger-test-infra:
    uses: alinpahontu2912/test-infra/.github/workflows/build_wheels_windows_arm64.yml@winarm64_wheels
    with:
      python_version: ${{ inputs.python_version || '3.12' }}
      msvc_version: ${{ inputs.msvc_version || 'latest' }}
      build_type: ${{ inputs.build_type || 'Release' }}
      repository_name: ${{ inputs.repository_name || 'pytorch/vision' }}
      repository_branch: ${{ inputs.repository_branch || 'main' }}
      build_version: ${{ inputs.build_version || '' }}