name: Build Windows Arm64 Torchvision Wheel

on:
  pull_request: null
  push:
    branches:
      - nightly
      - main
      - release/*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:
    inputs:
      repository_name:
        description: Torchvision repository (username/repo)
        required: false
        type: string
        default: pytorch/vision
      repository_branch:
        description: Repository branch
        required: false
        type: string
        default: main

permissions:
  id-token: write
  contents: read

jobs:
  trigger-test-infra:
    strategy:
      matrix:
        python_version: ["3.12"]
    uses: alinpahontu2912/test-infra/.github/workflows/build_wheels_windows_x64_test.yml@x64windows_test
    name: Build Windows x64 Torchvision Wheel  
    with:
        python_version: ${{ matrix.python_version }}
        repository_name: ${{ inputs.repository_name }}
        repository_branch: ${{ inputs.repository_branch }}
